import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import NavBar from "./NavBar";
import Sidebar from "./Sidebar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme accentColor="teal" grayColor="mauve">
          <NavBar />
          <main className="flex">
            <Sidebar />
            <div className="p-10">{children}</div>
          </main>
          {/* <ThemePanel/> */}
        </Theme>
      </body>
    </html>
  );
}
